### ISSUE TITLE
Not issue will remove once answer 😭

### ISSUE THREAD

**Issue by geegeekoby** [Dr-Sauce/uYouPlusUpdater#1]
Can you please make a scarlet version instead of troll store ❤️

**Comment by Dr-Sauce** [comment]
Sure. I’ll check if it’s possible and add it with AltStore.

**Comment by Dr-Sauce** [comment]
I’ve added support for AltStore, SideStore, Scarlet in 1.1.

However I couldn’t add full support for Scarlet. I need to know the URL scheme, but I couldn’t find it. So installing app updates with Scarlet won’t work. Only downloading and then manually installing will work.

**Here is what you’re gonna have to do:**
1. Launch uYouPlus Updater. Press ‘Update uYouPlus Updater to 1.1.
2. Install the update and open uYouPlus Updater. Press … and ‘Install/ Download Settings’. Choose ‘Download as file’ or ‘Offline Install’.
3. Press ‘Restart’. Press … again. And press ‘Install App Settings’. Select ‘Scarlet’.

**Comment by Dr-Sauce** [comment]
**Update:** Now supports Scarlet. (Got some help from the Scarlet dev)

Update to [uYouPlus Updater 1.2](https://github.com/Dr-Sauce/uYouPlusUpdater/releases/tag/1.2).

**Comment by geegeekoby** [comment]
Thank you
